manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hyx0329
      url-base: https://github.com/hyx0329
  projects:
    - name: zmk
      remote: hyx0329
      revision: soft-poweroff
      import: app/west.yml
  self:
    path: config
