manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: wslfung
      url-base: https://github.com/wslfung
  projects:
    - name: zmk
      remote: wslfung
      revision: features/soft-off-take-2
      import: app/west.yml
  self:
    path: config
